name: on-push
on:
  workflow_call:
    inputs:
      sonar_token:
        required: true
        type: secret
      gh_token:
        required: true
        type: secret
    secrets:
      sonar_token:
        required: true
      gh_token:
        required: true
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
